using System.Text;
using JetBrains.Annotations;

namespace LoonieTrader.Library.RestApi.Responses
{
    [UsedImplicitly(ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature, ImplicitUseTargetFlags.WithMembers)]
    public class ServiceEventsResponse
    {
        public Event[] events { get; set; }

        public override string ToString()
        {
            var resp = new StringBuilder();
            foreach (var evt in events)
            {
                resp.AppendLine(evt.ToString());
            }

            return resp.ToString();
        }

        public class Event
        {
            public Status status { get; set; }
            public string url { get; set; }
            public string timestamp { get; set; }
            public string sid { get; set; }
            public string message { get; set; }
            public bool informational { get; set; }

            public override string ToString()
            {
                var resp = new StringBuilder();

                resp.AppendFormat("id: {0}, name: {1}, description: {2}, url: {3}", this.sid, this.message, this.timestamp, this.url);

                if (status != null)
                {
                    resp.AppendLine();
                    resp.AppendFormat("id: {0}, name: {1}, description: {2}, url: {3}", status.id, status.name, status.description, status.url);
                }

                return resp.ToString();
            }
        }

        public class Status
        {
            public string description { get; set; }
            public string level { get; set; }
            public bool @default { get; set; }
            public string image { get; set; }
            public string url { get; set; }
            public string id { get; set; }
            public string name { get; set; }
        }
    }
}

/*
{"events":
[{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"},
"url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnoOUCgw", "timestamp": "Fri, 02 Sep 2016 21:29:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnoOUCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAq4iPCgw", "timestamp": "Fri, 02 Sep 2016 21:14:17 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAq4iPCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy9eWCgw", "timestamp": "Tue, 30 Aug 2016 20:54:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy9eWCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy8OHCgw", "timestamp": "Tue, 30 Aug 2016 20:49:16 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy8OHCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAueKRCQw", "timestamp": "Fri, 26 Aug 2016 22:44:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAueKRCQw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAwv2ECgw", "timestamp": "Fri, 26 Aug 2016 22:39:16 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAwv2ECgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAueKRCgw", "timestamp": "Fri, 26 Aug 2016 22:34:00 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAueKRCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnpmFCgw", "timestamp": "Fri, 26 Aug 2016 22:29:15 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnpmFCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAuYSACgw", "timestamp": "Fri, 19 Aug 2016 23:38:35 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAuYSACgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy-SDCgw", "timestamp": "Fri, 19 Aug 2016 23:03:03 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAy-SDCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA6ICfCQw", "timestamp": "Sat, 23 Jul 2016 01:30:00 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA6ICfCQw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA6ICfCgw", "timestamp": "Fri, 22 Jul 2016 21:25:10 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA6ICfCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA_KeQCww", "timestamp": "Wed, 13 Jul 2016 09:53:02 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA_KeQCww", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi82UCQw", "timestamp": "Wed, 13 Jul 2016 09:43:31 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi82UCQw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqNuOCgw", "timestamp": "Wed, 13 Jul 2016 09:38:05 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqNuOCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi5uNCgw", "timestamp": "Wed, 13 Jul 2016 08:58:31 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi5uNCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAgsyYCQw", "timestamp": "Wed, 13 Jul 2016 08:53:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAgsyYCQw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAgtCJCww", "timestamp": "Wed, 13 Jul 2016 08:13:33 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICAgtCJCww", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA2Z-eCQw", "timestamp": "Wed, 13 Jul 2016 08:08:26 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA2Z-eCQw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi9GFCgw", "timestamp": "Wed, 13 Jul 2016 06:38:30 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAi9GFCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAme6HCgw", "timestamp": "Wed, 13 Jul 2016 06:33:16 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAme6HCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA2Z-eCgw", "timestamp": "Wed, 13 Jul 2016 06:23:15 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA2Z-eCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDArfOLCgw", "timestamp": "Wed, 13 Jul 2016 06:18:10 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDArfOLCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqKabCgw", "timestamp": "Wed, 13 Jul 2016 06:13:30 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqKabCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAntKJCgw", "timestamp": "Wed, 13 Jul 2016 05:58:10 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAntKJCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA-tSHCgw", "timestamp": "Wed, 13 Jul 2016 05:53:15 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDA-tSHCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA_L2BCgw", "timestamp": "Fri, 08 Jul 2016 23:43:00 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgICA_L2BCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnqSQCgw", "timestamp": "Fri, 08 Jul 2016 21:23:03 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAnqSQCgw", "message": "Service is experiencing issues", "informational": false},
{"status": {"description": "The service is up", "level": "NORMAL", "default": true, "image": "http://api-status.oanda.com/images/icons/fugue/tick-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/up", "id": "up", "name": "Up"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqOiTCgw", "timestamp": "Fri, 22 Apr 2016 22:57:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAqOiTCgw", "message": "Service is running without issue", "informational": false},
{"status": {"description": "The service is currently down", "level": "NORMAL", "default": false, "image": "http://api-status.oanda.com/images/icons/fugue/cross-circle.png", "url": "http://api-status.oanda.com/api/v1/statuses/down", "id": "down", "name": "Down"}, "url": "http://api-status.oanda.com/api/v1/services/fxtrade-practice-rest-api/events/ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAuruLCgw", "timestamp": "Fri, 22 Apr 2016 21:52:01 GMT", "sid": "ahNzfm9hbmRhLXN0YXR1cy1wYWdlchILEgVFdmVudBiAgIDAuruLCgw", "message": "Service is experiencing issues", "informational": false}]}
*/
