Environment: Sandbox                                                          ## Sandbox, Practice, Live
ApiKey: 12345678901234567890123456789012-12345678901234567890123456789012     ## For the selected Environment
DefaultAccountId: 123-123-1234567-123                                         ##
UserId: 123456
FavouriteInstruments:
- USD_CAD
  EUR_USD
  EUR_GBP
